### ISSUE TITLE
remote site with Morningstar charge controller

### ISSUE THREAD

**Issue by jwrgorman** [SolarNetwork/solarnetwork#1]
i have a solar array for the search and rescue tower on a 14K mountain. i have a raspberry pi and a morningstar controller too. what should i do to get your software up and running?

**Comment by msqr** [comment]
See http://sourceforge.net/projects/solarnetwork/files/solarnode/pi/ for a Raspberry Pi OS image and instructions you can get started with. Once your node is running, use the Plugins setup screen to install the Morningstar plugin, and then configure that via the Settings screen.
