### ISSUE TITLE
wi-fi is not working in the latest solarnode version.  

### ISSUE THREAD

**Issue by lalitjoshi86** [SolarNetwork/solarnetwork#2]
I am trying to configure solarnode latest version .9 in raspberry pi 3 B. OS is successfully installed, however its not taking wifi inputs. 

Error is: solarnode wwpa_supplicant[960]: wlan0: Failed to initiate sched scan.

Please help me to fix it.

Regards, Lalit

**Comment by msqr** [comment]
Hi Lalit,

I assume you set up WiFi as described [in the wiki](https://github.com/SolarNetwork/solarnetwork/wiki/Node-OS-Networking). Can you share your `/etc/wpa_supplicant/wpa_supplicant-wlan0.conf` contents (minus the password)?

**Comment by msqr** [comment]
@lalitjoshi86 have you had any luck with getting WiFi going?

**Comment by msqr** [comment]
Closing from lack of response. Feel free to re-open with further feedback.
